Update ci-internal.yml

diff --git a/.github/workflows/ci-internal.yml b/.github/workflows/ci-internal.yml
--- a/.github/workflows/ci-internal.yml
+++ b/.github/workflows/ci-internal.yml
@@ -263,9 +263,10 @@ jobs:
               sudo installer -package ~/UnityIosModule.pkg -target /
             elif [[ ${{ inputs.os }} == 'ubuntu-latest' ]]; then
 
-              apt-get install -y unzip lib32stdc++6 lib32z1            
-              apt install gradle            
-              apt install lib32z1 lib32ncurses6 libbz2-1.0:i386 libstdc++6:i386
+              sudo apt-get install -y unzip lib32stdc++6 lib32z1            
+              sudo apt install gradle            
+              sudo apt install lib32z1 lib32ncurses6 libbz2-1.0:i386 libstdc++6:i386
+              sudo apt install libssl-dev              
 
               SDK_VERSION="6.0"
               NDK_VERSION="19.0.5232133"
@@ -276,38 +277,59 @@ jobs:
               SDK_DIR="${INSTALL_DIR}/SDK"
               NDK_DIR="${INSTALL_DIR}/NDK"
               JDK_DIR="${INSTALL_DIR}/OpenJDK"
+
+              # Clean up any previous incomplete installations
+              #rm -rf $SDK_DIR $NDK_DIR $JDK_DIR
               
               # Create directories and set permissions
               mkdir -p $INSTALL_DIR
               #chmod -R 777 /opt/Editor
+
+              original_dir=$(pwd)
               
-              # Clean up any previous incomplete installations
-              rm -rf $SDK_DIR $NDK_DIR $JDK_DIR
+              sudo mkdir -p /opt/Editor/Data/PlaybackEngines/AndroidPlayer
+              7z x ~/UnityAndroidModule.pkg -o/opt/Editor/Data/PlaybackEngines/AndroidPlayer
+              
+              cd /opt/Editor/Data/PlaybackEngines/AndroidPlayer
+              
+              # Check for the existence of Payload or Payload~
+              if [ -f Payload ]; then
+                # Decompress and extract Payload
+                zcat Payload | sudo cpio -idu && sudo rm Payload
+              elif [ -f Payload~ ]; then
+                # Extract Payload~
+                sudo cpio -idu < Payload~ && sudo rm Payload~
+              else
+                echo "Neither Payload nor Payload~ found. Exiting."
+                exit 1
+              fi             
+              
+              cd "$original_dir"          
+
+              # Install OpenJDK 1.8.0
+              wget https://github.com/adoptium/temurin8-binaries/releases/download/jdk-${JDK_VERSION}/OpenJDK8U-jdk_x64_linux_hotspot_${JDK_VERSION}.tar.gz -O openjdk.tar.gz
+              mkdir -p $JDK_DIR
+              tar -xzf openjdk.tar.gz -C $JDK_DIR --strip-components=1
               
               # Install Android SDK
               wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -O cmdline-tools.zip
               mkdir -p $SDK_DIR/cmdline-tools
               unzip cmdline-tools.zip -d $SDK_DIR/cmdline-tools
-              mv $SDK_DIR/cmdline-tools/cmdline-tools $SDK_DIR/cmdline-tools/latest
+              mv $SDK_DIR/cmdline-tools/cmdline-tools $SDK_DIR/cmdline-tools/latest           
               
+              # Accept licenses and install necessary packages
+              yes | sdkmanager --licenses
+              yes | sdkmanager --update
+              yes | sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
+
               # Set environment variables
               export JAVA_HOME=$JDK_DIR
               export ANDROID_HOME=$SDK_DIR
               export PATH=$JAVA_HOME/bin:$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
               export PATH=$ANDROID_HOME/platform-tools:$PATH
               
-              # Accept licenses and install necessary packages
-              yes | sdkmanager --licenses
-              yes | sdkmanager --update
-              yes | sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
-              
               # Remove duplicate platform-tools directory if it exists
               rm -rf /opt/Editor/Data/PlaybackEngines/AndroidPlayer/SDK/platform-tools-2
-              
-              # Install OpenJDK 1.8.0
-              wget https://github.com/adoptium/temurin8-binaries/releases/download/jdk-${JDK_VERSION}/OpenJDK8U-jdk_x64_linux_hotspot_${JDK_VERSION}.tar.gz -O openjdk.tar.gz
-              mkdir -p $JDK_DIR
-              tar -xzf openjdk.tar.gz -C $JDK_DIR --strip-components=1
               
               # Install Android NDK 19.0.5232133
               wget https://dl.google.com/android/repository/android-ndk-r19-linux-x86_64.zip -O android-ndk.zip
