Update ci-internal.yml

diff --git a/.github/workflows/ci-internal.yml b/.github/workflows/ci-internal.yml
--- a/.github/workflows/ci-internal.yml
+++ b/.github/workflows/ci-internal.yml
@@ -302,21 +302,21 @@ jobs:
               export ANDROID_SDK_ROOT="/opt/Editor/Data/PlaybackEngines/AndroidPlayer/SDK"
       
               # Install OpenJDK to the expected location
-              sudo apt-get install -y openjdk-11-jdk
-              sudo ln -s /usr/lib/jvm/java-11-openjdk-amd64/* /opt/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK
+              #sudo apt-get install -y openjdk-11-jdk
+              #sudo ln -s /usr/lib/jvm/java-11-openjdk-amd64/* /opt/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK
       
               # Create symbolic link for the Android SDK
               sudo ln -s $ANDROID_HOME/* /opt/Editor/Data/PlaybackEngines/AndroidPlayer/SDK
 
               # Set permissions to avoid 'permission denied' issues
-              sudo chmod -R 777 /opt/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK
+              #sudo chmod -R 777 /opt/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK
               sudo chmod -R 777 /opt/Editor/Data/PlaybackEngines/AndroidPlayer/SDK
 
               # Verify JDK installation
-              if [ ! -d "/opt/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK" ]; then
-                echo "JDK installation failed. Exiting."
-                exit 1
-              fi
+              #if [ ! -d "/opt/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK" ]; then
+              #  echo "JDK installation failed. Exiting."
+              #  exit 1
+              #fi
       
               # Verify Android SDK installation
               if [ ! -d "/opt/Editor/Data/PlaybackEngines/AndroidPlayer/SDK" ]; then
